config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
    resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
    resources :product_models, only: [:index, :new, :create, :show]

    resources :orders, only: [:index, :show, :new, :create, :edit, :update] do

      resources :order_items, only: [:new, :create]

      get 'search', on: :collection
      post 'delivered', on: :member
      post 'cancel', on: :member
    end

    authenticate :user do
      resources :product_models, only: [:index, :new, :create, :show]
    end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  has_many :order_items
  has_many :orders, through: :order_items
  
  validates :name, :sku, presence:true
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @product_models = ProductModel.all
  end

  def new
    @product_model = ProductModel.new
    @suppliers = Supplier.all
  end

  def create
    product_model_params = params.require(:product_model).permit(:name, :height, :width, :depth,
                                                                  :weight, :sku, :supplier_id)
    
    @product_model= ProductModel.new(product_model_params)
    if @product_model.save
      redirect_to @product_model, notice: 'Modelo de produto cadastrado com sucesso'
    else
      @suppliers = Supplier.all
      flash.now[:notice] = 'Não foi possivel cadastrar o modelo de produto.'
      render 'new'
    end
  end

  def show
    @product_model = ProductModel.find(params[:id])

  end
end

app/views/product_models/index.html.erb
<div class="container mt-4">
  <h1 class="mb-4">Modelos de Produtos</h1>

  <%= link_to new_product_model_path, class: 'btn btn-outline-light mb-4 d-inline-flex align-items-center' do %>
    <i class="bi bi-plus-circle me-2"></i>
    <span>Cadastrar Novo</span>
  <% end %>

  <% if @product_models.any? %>
    <div class="row row-cols-1 row-cols-md-3 g-4">
      <% @product_models.each do |pm| %>
        <div class="col">
          <div class="card h-100">
            <div class="card-body">
              <h2 class="card-title h5"><%= pm.name %></h2>
              <dl>
                <dt class="text-muted">SKU</dt>
                <dd><%= pm.sku %></dd>
                <dt class="text-muted">Fornecedor</dt>
                <dd><%= pm.supplier.brand_name %></dd>
              </dl>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="alert alert-info">
      Nenhum modelo de produto cadastrado
    </div>
  <% end %>
</div>

app/views/product_models/new.html.erb
<div class="container mt-4">
  <h1 class="mb-4">Cadastrar Novo Modelo de Produto</h1>

  <%= form_with(model: @product_model) do |f| %>
    <div class="row">
      <div class="col-md-6">
        <div class="mb-3">
          <%= f.label :name, class: "form-label" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :weight, class: "form-label" %>
          <%= f.number_field :weight, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :height, class: "form-label" %>
          <%= f.text_field :height, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :sku, class: "form-label" %>
          <%= f.text_field :sku, class: "form-control" %>
        </div>
      </div>

      <div class="col-md-6">
        <div class="mb-3">
          <%= f.label :width, class: "form-label" %>
          <%= f.text_field :width, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :depth, class: "form-label" %>
          <%= f.text_field :depth, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :supplier_id, class: "form-label" %>
          <%= f.collection_select :supplier_id, @suppliers, :id, :brand_name, {}, class: "form-select" %>
        </div>
      </div>
    </div>

    <div class="mt-3">
      <%= f.submit 'Enviar', class: "btn btn-dark px-4 border border-white" %>
      <%= link_to 'Voltar', root_path, class: "btn btn-dark px-4 border border-white ms-2" %>
    </div>
  <% end %>
</div>

app/views/product_models/show.html.erb
<h1><%= @product_model.name %></h1>

<dl>
<dt>Fornecedor:</dt>
<dd><%= @product_model.supplier.brand_name %></dd>
<dt>SKU:</dt>
<dd><%= @product_model.sku %></dd>
<dt>Dimensão:<dt>
<dd><%= @product_model.height %>cm x <%= @product_model.width %>cm x <%= @product_model.depth %>cm</dd>
<dt>Peso:</dt>
<dd><%= @product_model.weight %>g<dd>
</dl>