config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
    resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
    resources :product_models, only: [:index, :new, :create, :show]

    resources :orders, only: [:index, :show, :new, :create, :edit, :update] do

      resources :order_items, only: [:new, :create]

      get 'search', on: :collection
      post 'delivered', on: :member
      post 'cancel', on: :member
    end

    authenticate :user do
      resources :product_models, only: [:index, :new, :create, :show]
    end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  belongs_to :supplier
  belongs_to :user
  has_many :order_items
  has_many :stock_products

  enum status: { pending: 0, delivered: 1, canceled: 2 }

  validates :code, presence: true, uniqueness: true
  validates :estimated_delivery_date, presence: true
  validate :estimated_delivery_date_is_future, on: :create

  before_validation :generate_code, on: :create

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end

  def estimated_delivery_date_is_future
    if self.estimated_delivery_date.present? && self.estimated_delivery_date <= Date.today
      errors.add(:estimated_delivery_date, " deve ser futura.")
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user_permission, only: [:show, :edit, :delivered]
  
  def index
    @orders = current_user.orders
  end

  def new
    @order = Order.new
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def create
    order_params = params.require(:order).permit(:warehouse_id, :supplier_id, :estimated_delivery_date)
    @order = Order.new(order_params)
    @order.user = current_user
    if @order.save
      redirect_to @order, notice: "Pedido registrado com sucesso."
    else
      @warehouses = Warehouse.all
      @suppliers = Supplier.all
      flash.now[:alert] = "Não foi possível registrar o pedido."
      render :new
  end
end

  def show
  end

  def search
    @orders = Order.where('code LIKE ?', "%#{params[:query]}%")
  end

  def edit
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def update
    order_params = params.require(:order).permit(:warehouse_id, :supplier_id, :estimated_delivery_date)
    @order = Order.find(params[:id])
    if @order.user != current_user
      redirect_to root_path, alert: 'Você não possui acesso a este pedido'
    else
      if @order.update(order_params)
        redirect_to @order, notice: 'Pedido atualizado com sucesso'
      else
        @warehouses = Warehouse.all
        @suppliers = Supplier.all
        flash.now[:alert] = 'Não foi possível atualizar o pedido'
        render :edit
      end
    end
  end

  def delivered
    @order.delivered!
    @order.order_items.each do |item|
      item.quantity.times do
        StockProduct.create!(order: @order, product_model: item.product_model,
                             warehouse: @order.warehouse)
      end
    end

    redirect_to @order, notice: 'Pedido marcado como entregue'
  end

  def cancel
    order = Order.find(params[:id])
    order.update(status: :canceled)
    redirect_to order
  end


  private

  def check_user_permission
    @order = Order.find(params[:id])
    if @order.user != current_user
      return redirect_to root_path, alert: 'Você não possui acesso a este pedido'
    end
  end
end

app/views/orders/_form.html.erb
<%= form_with(model: @order) do |f| %>
  <div class="mb-3 col-md-6">
    <%= f.label :warehouse_id, 'Galpão Destino', class: "form-label" %>
    <%= f.collection_select :warehouse_id, @warehouses, :id, :full_description, {}, class: "form-select" %>
  </div>
  <div class="mb-3 col-md-6">
    <%= f.label :supplier_id, 'Fornecedor', class: "form-label" %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :corporate_name, {}, class: "form-select" %>
  </div>
  <div class="mb-3 col-md-6">
    <%= f.label :estimated_delivery_date, 'Data Prevista de Entrega', class: "form-label" %>
    <%= f.date_field :estimated_delivery_date, class: "form-control" %>
  </div>
  
  <div class="mb-3">
    <%= f.submit 'Gravar', class: "btn btn-dark border-light" %>
  </div>
<% end %>

app/views/orders/_order.html.erb
  <dl>
    <dt><%= Order.human_attribute_name(:code) %>:</dt>
    <dd><%= link_to order.code, order %></dd>
    <dt><%= Order.human_attribute_name(:warehouse_id) %>:</dt>
    <dd><%= order.warehouse.full_description %></dd>
    <dt><%= Order.human_attribute_name(:supplier_id) %>:</dt>
    <dd><%= order.supplier.corporate_name %></dd>
    <dt><%= Order.human_attribute_name(:status) %>:</dt>
    <dd><%= I18n.t(order.status) %></dd>
  </dl>

app/views/orders/edit.html.erb
<%= render 'form' %>

app/views/orders/index.html.erb
<h1 class="mb-4">Meus Pedidos</h1>

<% @orders.each do |order| %>
  <div class="card mb-4">
    <div class="card-body">
      <div class="row">
        <div class="col-md-6">
          <p class="card-text mb-2">
            <strong>Código do Pedido:</strong> 
            <%= link_to order.code, order_path(order), class: 'text-decoration-none' %>
          </p>
          <p class="card-text mb-2">
            <strong>Galpão Destino:</strong> 
            <%= order.warehouse.name %>
          </p>
          <p class="card-text mb-2">
            <strong>Data Prevista:</strong> 
            <%= order.estimated_delivery_date.strftime('%d/%m/%Y') %>
          </p>
        </div>
        <div class="col-md-6">
          <p class="card-text mb-2">
            <strong>Fornecedor:</strong> 
            <%= order.supplier.corporate_name %>
          </p>
          <p class="card-text mb-2">
            <strong>Usuário Responsável:</strong> 
            <%= order.user.name %>
          </p>
          <p class="card-text mb-2">
            <strong>Status:</strong> 
            <span class="badge bg-secondary"><%= t(order.status) %></span>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/orders/new.html.erb
<div class="container mt-4 bg-dark text-white">
  <h1>Registrar Pedido</h1>

  <% if @order.errors.any? %>
    <div class="error-messages">
      <% @order.errors.full_messages.each do |message| %>
        <p class="text-danger"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <%= render 'form' %>
</div>

app/views/orders/search.html.erb
<h1>Resultados da Busca por: <%= params[:query] %></h1>
<p><%= @orders.count %> pedido(s) encontrado(s)</p>

<% @orders.each do |order| %>
  <div>
    <h3>Código: <%= link_to order.code, order_path(order) %></h3>
    <dl>
      <dt>Galpão Destino:</dt>
      <dd><%= order.warehouse.full_description %></dd>
      
      <dt>Fornecedor:</dt>
      <dd><%= order.supplier.corporate_name %></dd>
      
      <dt>Situação do Pedido:</dt>
      <dd><%= I18n.t(order.status) %></dd>
    </dl>
  </div>
<% end %>

app/views/orders/show.html.erb
<div class="container mt-4 bg-dark text-white">
  <h1 class="mb-4">Detalhes do Pedido</h1>
  <h2 class="h4 mb-3"><%= Order.model_name.human %> <%= @order.code %></h2>

  <div class="card bg-dark border-light mb-4">
    <div class="card-body">
      <dl class="row">
        <dt class="col-sm-3 text-white"><%= Order.human_attribute_name(:warehouse_id) %>:</dt>
        <dd class="col-sm-9 text-white"><%= @order.warehouse.full_description %></dd>
        
        <dt class="col-sm-3 text-white"><%= Order.human_attribute_name(:supplier_id) %>:</dt>
        <dd class="col-sm-9 text-white"><%= @order.supplier.corporate_name %></dd>
        
        <dt class="col-sm-3 text-white"><%= Order.human_attribute_name(:user_id) %>:</dt>
        <dd class="col-sm-9 text-white"><%= @order.user.description %></dd>
        
        <dt class="col-sm-3 text-white"><%= Order.human_attribute_name(:estimated_delivery_date) %>:</dt>
        <dd class="col-sm-9 text-white"><%= I18n.localize(@order.estimated_delivery_date) %></dd>
        
        <dt class="col-sm-3 text-white"><%= Order.human_attribute_name(:status) %>:</dt>
        <dd class="col-sm-9 text-white"><%= I18n.t(@order.status) %></dd>
      </dl>
    </div>
  </div>

  <h2 class="h4 mb-3">Itens do Pedido</h2>
  <%= link_to 'Adicionar Item', new_order_order_item_path(@order.id), class: 'btn btn-dark border-light mb-3' %>

  <div class="list-group mb-4">
    <% @order.order_items.each do |item| %>
      <div class="list-group-item bg-dark border-light text-white">
        <%= item.quantity %> x <%= item.product_model.name %>
      </div>
    <% end %>
  </div>

  <div class="mb-3">
    <% if @order.pending? %>
      <div class="mb-3">
        <%= button_to 'Cancelar Pedido', 
                      cancel_order_path(@order), 
                      method: :post,
                      class: 'btn btn-dark border-danger text-danger me-2',
                      style: 'display: inline-block' %>
      </div>
      
      <div class="mb-3">
        <%= button_to 'Marcar como Entregue', 
                      delivered_order_path(@order), 
                      method: :post,
                      class: 'btn btn-dark border-success text-success',
                      style: 'display: inline-block' %>
      </div>
    <% end %>
  </div>

  <%= link_to 'Editar', edit_order_path(@order.id), class: 'btn btn-dark border-light mb-3' %>