config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
    resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
    resources :product_models, only: [:index, :new, :create, :show]

    resources :orders, only: [:index, :show, :new, :create, :edit, :update] do

      resources :order_items, only: [:new, :create]

      get 'search', on: :collection
      post 'delivered', on: :member
      post 'cancel', on: :member
    end

    authenticate :user do
      resources :product_models, only: [:index, :new, :create, :show]
    end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_many :product_models
    validates :corporate_name, :brand_name, :registration_number, 
                :full_address, :city, :state, :email, presence: true
end
  

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def index
    @suppliers = Supplier.all
  end

  def show
    @supplier = Supplier.find(params[:id])
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to @supplier, notice: 'Fornecedor cadastrado com sucesso'
    else
      flash.now[:alert] = 'Fornecedor não cadastrado'
      render 'new'
    end
  end

  def edit
    @supplier = Supplier.find(params[:id])
  end

  def update
    @supplier = Supplier.find(params[:id])
  end

  private
  def supplier_params
    params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number,
                                      :full_address, :city, :state, :email) #
  end


end

app/views/suppliers/edit.html.erb
<div class="container mt-4">
  <h1 class="mb-4">Novo Fornecedor</h1>

  <%= form_with(model: @supplier) do |f| %>
    <div class="row">
      <div class="col-md-6">
        <div class="mb-3">
          <%= f.label :corporate_name, class: "form-label" %>
          <%= f.text_field :corporate_name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :brand_name, class: "form-label" %>
          <%= f.text_area :brand_name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :full_address, class: "form-label" %>
          <%= f.text_field :full_address, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :registration_number, class: "form-label" %>
          <%= f.text_field :registration_number, class: "form-control" %>
        </div>
      </div>

      <div class="col-md-6">
        <div class="mb-3">
          <%= f.label :city, class: "form-label" %>
          <%= f.text_field :city, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :state, class: "form-label" %>
          <%= f.text_field :state, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :email, class: "form-label" %>
          <%= f.text_field :email, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-12">
        <%= f.submit 'Enviar', class: 'btn btn-outline-light d-inline-flex align-items-center' do %>
          <i class="bi bi-send me-2"></i>
          <span>Enviar</span>
        <% end %>
        <%= link_to suppliers_path, class: 'btn btn-outline-secondary ms-2 d-inline-flex align-items-center' do %>
          <i class="bi bi-arrow-left me-2"></i>
          <span>Voltar</span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/suppliers/index.html.erb
<div class="container mt-4">
  <h1 class="mb-4">Fornecedores</h1>

  <% if @suppliers.any? %>
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead class="table-dark">
          <tr>
            <th>Nome</th>
            <th>Localização</th>
          </tr>
        </thead>
        <tbody>
          <% @suppliers.each do |supplier| %>
            <tr>
              <td><%= link_to supplier.brand_name, supplier, class: "text-decoration-none" %></td>
              <td><%= supplier.city %> - <%= supplier.state %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="alert alert-info">
      Não existem fornecedores cadastrados
    </div>
  <% end %>

  <%= link_to new_supplier_path, class: "btn btn-outline-light d-inline-flex align-items-center" do %>
    <i class="bi bi-plus-circle me-2"></i>
    <span>Cadastrar novo fornecedor</span>
  <% end %>
</div>

app/views/suppliers/new.html.erb
<div class="container mt-4">
  <h1 class="mb-4">Novo Fornecedor</h1>

  <% if(@supplier.errors.any?) %>
    <div class="alert alert-danger">
      <p>Verifique os erros abaixo:</p>
      <ul>
        <% @supplier.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @supplier, class: 'row g-3') do |f| %>
    <div class="col-md-6">
      <%= f.label :corporate_name, class: 'form-label' %>
      <%= f.text_field :corporate_name, class: 'form-control' %>
    </div>
    <div class="col-md-6">
      <%= f.label :brand_name, class: 'form-label' %>
      <%= f.text_field :brand_name, class: 'form-control' %>
    </div>
    <div class="col-12">
      <%= f.label :full_address, class: 'form-label' %>
      <%= f.text_field :full_address, class: 'form-control' %>
    </div>
    <div class="col-md-6">
      <%= f.label :registration_number, class: 'form-label' %>
      <%= f.text_field :registration_number, class: 'form-control' %>
    </div>
    <div class="col-md-4">
      <%= f.label :city, class: 'form-label' %>
      <%= f.text_field :city, class: 'form-control' %>
    </div>
    <div class="col-md-2">
      <%= f.label :state, class: 'form-label' %>
      <%= f.text_field :state, class: 'form-control' %>
    </div>
    <div class="col-md-6">
      <%= f.label :email, class: 'form-label' %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="col-12 mt-3">
      <%= f.submit 'Cadastrar novo fornecedor', class: 'btn btn-secondary text-white border-white hover-opacity' %>
    </div>
  <% end %>
  
  <div class="mt-3">
    <%= link_to 'Voltar', suppliers_path, class: 'btn btn-outline-secondary' %>
  </div>
</div>

app/views/suppliers/show.html.erb
<h1>Fornecedor <%= @supplier.brand_name %></h1>
<h2><%= @supplier.corporate_name %></h2>

<dl>
  <dt>Documento:</dt>
  <dd><%= @supplier.registration_number %></dd>
  <dt>Endereço:</dt>
  <dd><%= @supplier.full_address %> - <%= @supplier.city %> - <%= @supplier.state %></dd>
  <dt>E-mail:</dt>
  <dd><%= @supplier.email %></dd>
</dl>

<%= link_to 'Editar', edit_supplier_path(@supplier), class: 'btn btn-dark' %>

<div>
  <%= link_to 'Voltar', root_path, class: 'btn btn-light' %>
</div>